services:
  postgres:
    image: postgres:17.0-bookworm
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kertu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  interactive_server:
    build:
      context: .
      dockerfile: Kertu.Solution/Kertu.InteractiveServer/Dockerfile
    container_name: interactive_server
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      POSTGRES_DB: kertu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=kertu;Username=postgres;Password=password"
    volumes:
      - data_protection_keys:/root/.aspnet/DataProtection-Keys
    ports:
      - "80:8080"

volumes:
  postgres_volume:
  data_protection_keys:
