name: Publish Docker image

on:
  push:
    branches: 
      - "github-actions"
      - "main"
      - "workflow-test"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Compose
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          echo "DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}" > .env
          echo "POSTGRES_DB=${POSTGRES_DB}" >> .env
          echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
      - name: Check Docker Compose version
        run: docker compose version
      - name: Build and push Docker images with Docker Compose
        run: |
          docker compose -f docker-compose.yml -f docker-compose.override.yml build
          docker compose -f docker-compose.yml -f docker-compose.override.yml push
